language: julia
os:
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'versioninfo(); Pkg.init(); Pkg.clone(pwd()); Pkg.test("FactCheck", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("FactCheck")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
